package gtb.api.unification.materials;

import gregtech.api.unification.material.Material;

import gtb.api.unification.materials.info.GTBMaterialFlags;
import gtb.api.unification.materials.info.GTBMaterialIconSet;

public class GTBMaterials {

    // Biological Materials

    public static Material PolyhydroxylAlkanoate;
    public static Material YButyrolacetone;
    public static Material PalmOil;
    public static Material OrthophosphoricAcidSolution;
    public static Material OrthophosphoricAcid;
    public static Material PhosphoricAnihydride;
    public static Material MethyleneDiphosphoricAcid;
    public static Material PapaicDigestOfSoybeanMeal;
    public static Material BeanSlurry;
    public static Material Rhizobium;
    public static Material DefattedSoybeanFlour;
    public static Material SoybeanOil;
    public static Material CrushedSoybean;
    public static Material Trypsin;
    public static Material HomogenizedPancreasMixture;
    public static Material AlphaLinolenicAcid;
    public static Material SolidMilkResidues;
    public static Material MilkOil;
    public static Material HeatedMilkSlurry;
    public static Material PeptoneMixture;
    public static Material PhenylEthylAlcoholBloodAgar;
    public static Material PhenylEthylAlcohol;
    public static Material PhenylEthylAlcoholAgarSolution;
    public static Material DissolvedPhenylEthylAlcoholAgar;
    public static Material SolidifiedSterileDefibernatedSheepBlood;
    public static Material EdeticAcid;
    public static Material DefibernatedSheepBlood;
    public static Material SheepBloodPlasma;
    public static Material SheepBloodCells;
    public static Material Fructose;
    public static Material Iriditus;
    public static Material EschericiaColi;
    public static Material EthyleneGlycol;
    public static Material Nonylphenol;
    public static Material EthoxylatedNonylphenol;
    public static Material Nonoxynol_9_Solution;
    public static Material Nonoxynol_9;
    public static Material Glucose;
    public static Material SolidGrain;
    public static Material Wort;
    public static Material HotGristSolution;
    public static Material GristPowder;
    public static Material Peptone;
    public static Material MaltExtract;
    public static Material NutrientRichSolution;
    public static Material WasteWater;
    public static Material YeastMixture;
    public static Material Mannitol;
    public static Material YeastExtract;
    public static Material DissolvedYeastExtractMannitolMixture;
    public static Material YeastExtractMannitolAgarSolution;
    public static Material YeastExtractMannitolMedium;
    public static Material YEEMSolution;
    public static Material CupriavidusNecator;
    public static Material CupriavidusNecatorBacteriaSample;
    public static Material BacterialGrowthMedium;
    public static Material BloodCells;
    public static Material BloodPlasma;
    public static Material Blood;
    public static Material Catalase;
    public static Material DepletedBacterialGrowthMedium;
    public static Material BasicFibroblastGrowthMedium;
    public static Material EpidermalGrowthFactor;
    public static Material HundredEthanol;
    public static Material HundredMethanol;
    public static Material HundredButanol;
    public static Material Cuproquin;
    public static Material Sulfanilamide;
    public static Material AcetylsulfanilylChloride;
    public static Material ChlorosulfonicAcid;
    public static Material AceticAnhydride;
    public static Material Aniline;
    public static Material AmmoniumNitrate;
    public static Material B_27_Supplement;
    public static Material Glutamine;
    public static Material LinoleicAcid;
    public static Material Biotin;
    public static Material Ethanolamine;
    public static Material VitaminA;
    public static Material BetaIonone;
    public static Material PropargylChloride;
    public static Material Citral;
    public static Material BetaPinene;
    public static Material Turpentine;
    public static Material PropargylAlcohol;
    public static Material Acetylene;
    public static Material CleanAmmoniaSolution;
    public static Material BrevibacteriumFlavium;
    public static Material Yeast;
    public static Material Leucine;
    public static Material BetaPineneSolution;
    public static Material SheepBlood;
    public static Material Xerizin;

    // Element Materials
    // FD Materials

    public static Material MagnesiumChlorideSolution;
    public static Material DilutedRubidiumSolution;
    public static Material DilutedCaesiumSolution;
    public static Material Alumina;
    public static Material StannicChloride;
    public static Material RubidiumChlorostannate;
    public static Material CaesiumChlorostannate;
    public static Material HeavyAlkaliChlorideSolution;
    public static Material TinFourChloride;
    public static Material WaelzOxide;
    public static Material WaelzSlag;
    public static Material ImpureGermaniumDioxide;
    public static Material RoastedSphalerite;
    public static Material ZincRichSphalerite;
    public static Material GermaniumTetrachloride;
    public static Material GermaniumDioxide;
    public static Material ZincOxide;
    public static Material CarbonSulfide;
    public static Material Tributylamine;
    public static Material IsoOctane;
    public static Material AlkylatedAdamantanes;
    public static Material EnrichedNaquadahCompound;
    public static Material NaquadriaticCompound;
    public static Material Triphenylphosphine;
    public static Material FluorodarmstadticAcid;
    public static Material AntimonyPentafluoride;
    public static Material Ozone;
    public static Material DarmstadtiumCatalyst;
    public static Material BioPlastic;
    public static Material Photopolymer;
    public static Material AluminiumChloride;
    public static Material CucrmgbaCatalyst;
    public static Material OneFourButynediol;
    public static Material OneFourButanediol;
    public static Material PotassiumHydroxide;
    public static Material PotassiumManganate;
    public static Material SodiumEthoxide;
    public static Material BoricAcid;
    public static Material SodiumHydride;
    public static Material SodiumBorohydride;
    public static Material SodiumHydroxideSolution;
    public static Material HotWater;
    public static Material ActivatedCarbon;
    public static Material EthyleneOxide;
    public static Material PhosphorusSolution;
    public static Material Trichloroflerane;
    public static Material LiquidEnrichedHelium_4;
    public static Material Helium_4;
    public static Material SuperFluidHelium_4;
    public static Material VeryHotNitrogen;
    public static Material SiliconCarbideVapor;
    public static Material SiliconCarbide;
    public static Material LiquidXenon;
    public static Material ExtraDistilledWater;
    public static Material NaquadahDioxide;
    public static Material ElectronDegenerateRhenium;
    public static Material ElectronDegenerateRheniumPlasma;
    public static Material HighPurityArsenic;
    public static Material WhitePhosphorus;
    public static Material NovolacsPhotoresist;
    public static Material IndiumChloride;
    public static Material PlatinumConcentrate;
    public static Material PlatinumExtract;
    public static Material PalladiumExtract;
    public static Material PlatinumResidues;
    public static Material PotassiumDisulfate;
    public static Material LeachResidue;
    public static Material SodiumRuthenate;
    public static Material RutheniumTetroxideLiquid;
    public static Material IridiumDioxide;
    public static Material PlatinumSolution;
    public static Material PlatinumSalt;
    public static Material PalladiumMotherLiqour;
    public static Material PalladiumSalt;
    public static Material PalladiumMetallicPowder;
    public static Material Nonene;
    public static Material Propylene;
    public static Material Hexane;
    public static Material Pentane;
    public static Material NHexadecane;
    public static Material NHeptane;
    public static Material NOctane;
    public static Material ZSM5;
    public static Material OXylene;
    public static Material PXylene;
    public static Material MPXylene;
    public static Material MXylene;
    public static Material NPropanol;
    public static Material NButanol;
    public static Material IsoamylAlcohol;
    public static Material IsobutylAlcohol;
    public static Material Formaldehyde;
    public static Material Dicyclopentadiene;
    public static Material Cyclopentadiene;
    public static Material HydrogenPeroxide;
    public static Material TungstenTrioxide;
    public static Material CalciumHydroxide;
    public static Material LithiumHydroxide;
    public static Material SodiumTungstate;
    public static Material CalciumTungstate;
    public static Material LithiumHydroxideSolution;
    public static Material LithiumFluoride;
    public static Material Polyetheretherketone;
    public static Material PhotopolymerSolution;
    public static Material UsedPhotopolymerSolution;
    public static Material VeryHotXenon;
    public static Material VeryHotArgon;
    public static Material NickelNitride;
    public static Material VanadiumTrichloride;
    public static Material LiquidHelium;
    public static Material MetastableOganesson;
    public static Material VeryHotKrypton;
    public static Material NaquadahRichSterileGrowthMedium;
    public static Material HighDensityPolyethylene;
    public static Material LiquidNitrogen;
    public static Material GrapheneOxidationSolution;
    public static Material GraphiteOxide;
    public static Material GrapheneOxide;
    public static Material GrapheneOxidationResidues;
    public static Material SilverBromide;
    public static Material Silane;
    public static Material Trichlorosilane;
    public static Material ChloronaquadicAcid;
    public static Material VeryHotAquaRegia;
    public static Material SodiumNitrate;
    public static Material BariumTitanate;
    public static Material HydrogenChloride;
    public static Material ZBLAN;
    public static Material DopedNanotubeDepositionMixture;
    public static Material NanotubeDepositionMix;
    public static Material DopedNanotubeDepositionMix;
    public static Material CarbonNanotubes;
    public static Material LiquidCrystalDetector;
    public static Material FullerenePolymerMatrix;
    public static Material FullerenePolymerTetrix;
    public static Material SeaborgiumDopedNanotubes;
    public static Material NaquadriaticTaranium;
    public static Material ChromaticGlass;
    public static Material SuperFluidHelium;
    public static Material SaltFreeBrine;
    public static Material LithiumChlorideSolution;
    public static Material BoronFreeSolution;
    public static Material Grisium;
    public static Material SodiumSulfideSolution;

    // SD Materials
    public static Material CalciumSalts;
    public static Material SodiumSalts;
    public static Material PotassiumMagnesiumSalts;
    public static Material PalladiumEnrichedAmmonia;
    public static Material AcidicIridiumDioxide;
    public static Material ReprecipitatedPalladium;
    public static Material RutheniumTetroxideSolution;
    public static Material RhodiumSulfateSolution;
    public static Material Tetrapropylammoniumbromide;
    public static Material Ethylenediamine;
    public static Material UEVSuperconductor;

    // Unknown Materials
    public static Material ConcentratedBrine;
    public static Material DampBromine;
    public static Material IodineSlurry;
    public static Material CrudeBromineSolution;
    public static Material Brine;
    public static Material BrominatedBrine;
    public static Material IodizedBrine;
    public static Material GrainsOfInfinity;
    public static Material WetBedrockDust;
    public static Material OilyBedrockDust;
    public static Material BedrockContaminatedOil;
    public static Material SodiumIsobutylXanthate;
    public static Material FineBedrockDust;
    public static Material Adamantite;
    public static Material EnrichedNaquadahNitrate;
    public static Material NaquadriaNitrate;
    public static Material PrecipitateMithril;
    public static Material RoughenMithril;
    public static Material ExcitedRoughenMithril;
    public static Material ExcitedMithril;
    public static Material Mithril;
    public static Material Perfluorotributylamine;
    public static Material BedrockSlurry;
    public static Material PurifiedBedrockSlurry;
    public static Material AdamantaneRichOilSolution;
    public static Material LiquidOzone;
    public static Material TriniumSolution;
    public static Material AdamantiumPentoxide;
    public static Material AdamantiumPhosphorusHydrogenPlasma;
    public static Material GaseousAdamantane;
    public static Material MoltenAdamantiumDioxide;
    public static Material MithrilFluoride;
    public static Material AdamantaneLubricant;
    public static Material Adamantane;
    public static Material IodizedOil;
    public static Material HydroCrackedKerosene;
    public static Material SteamCrackedKerosene;
    public static Material PlatinumExtractionMixture;
    public static Material DilutedOil;
    public static Material DesaltedOil;
    public static Material SulfuricKerosene;
    public static Material SulfuricDiesel;
    public static Material SulfuricOilResidues;
    public static Material SulfuricGasoline;
    public static Material Resin;
    public static Material Kerosene;
    public static Material SulfuricFuelOil;
    public static Material FuelOil;
    public static Material Furfural;
    public static Material BTEX;
    public static Material EthanolWaterAzeotrope;
    public static Material FuselOil;
    public static Material ImpureEthanol;
    public static Material GrainSolution;
    public static Material Vinegar;
    public static Material FractionC_5;
    public static Material LubricantMixture;
    public static Material SlackWax;
    public static Material AlkylatedNaturalGas;
    public static Material Syngas;

    // Organic Chemistry Materials
    public static Material FormicAcid;
    public static Material SodiumFormate;
    public static Material Tripropylamine;

    // Fantasy Materials
    public static Material AwakenedDraconium;
    public static Material Adamantium;
    public static Material Pikyonium;
    public static Material CosmicNeutronium;
    public static Material Infinity;
    public static Material Eternal;
    public static Material TemporallyConstrainedAntiMatter;
    public static Material CataclysmInducedMixedMatter;

    public static void init() {
        GTBMaterialPropertyAddition.init();
        GTBMaterialFlags.add();
        GTBMaterialIconSet.set();
        GTBElementMaterials.register();
        GTBFirstDegreeMaterials.register();
        GTBSecondDegreeMaterials.register();
        GTBOrganicChemistryMaterials.register();
        GTBUnknownCompositionMaterials.register();
        GTBBiologicalMaterials.register();
        GTBFantasyMaterials.register();
        GTBMaterialSetFormula.init();
        GTBMaterialIconSet.set();
    }
}
